INSERT INTO users (username, password, role, created_at, updated_at) VALUES
                                                                         ('admin', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_ADMIN', NOW(), null),
                                                                         ('fnavas', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('sarah_jenkins', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('michael_smith', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('emily_rose', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('david_miller', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('jessica_vance', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('ryan_cooper', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('olivia_p', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('kevin_dev', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('linda_blair', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('brian_foster', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('megan_fox', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('chris_evans', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('sophia_lane', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('peter_parker', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('anna_scott', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('robert_downey', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('lucy_liu', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null),
                                                                         ('tom_hanks', '$2a$10$v437ar7Mkhi/AfKDxgFw/u9gK3LSRfo3Hv1P1YNOsMj6ZT5F5kFxa', 'ROLE_USER', NOW(), null);

INSERT INTO posts (title, content, author_id, created_at, updated_at) VALUES
-- User 1: admin_chief (Tech & Admin)
('Mastering Spring Boot Security', 'A comprehensive guide to implementing JWT and OAuth2 in your microservices.', 1, NOW(), NOW()),
('Linux Server Hardening', 'Top 10 essential steps to secure your production servers against common threats.', 1, NOW(), NOW()),
('PostgreSQL Performance Tuning', 'Learn how to optimize your queries using indexing and explain analyze.', 1, NOW(), NOW()),
('The Future of Cloud Computing', 'Exploring the transition from monolithic architectures to serverless functions.', 1, NOW(), NOW()),
('Docker Best Practices', 'How to create slim, secure, and efficient container images for your apps.', 1, NOW(), NOW()),

-- User 2: alex_walker (Travel & Adventure)
('Hidden Gems in Europe', 'Discover the most underrated cities you should visit this summer.', 2, NOW(), NOW()),
('Solo Backpacking Guide', 'Everything you need to know about traveling the world with just a carry-on.', 2, NOW(), NOW()),
('Tokyo: A Local Experience', 'Moving beyond the tourist traps to find the heart of Japan.', 2, NOW(), NOW()),
('Budget Travel Hacks', 'How I traveled through Southeast Asia for less than $30 a day.', 2, NOW(), NOW()),
('The Best Travel Insurance', 'A detailed comparison of policies for digital nomads and expats.', 2, NOW(), NOW()),

-- User 3: sarah_jenkins (Food & Baking)
('The Science of Sourdough', 'Understanding fermentation and how to keep your starter alive forever.', 3, NOW(), NOW()),
('Quick Weeknight Dinners', 'Healthy meals you can prepare in under 30 minutes after work.', 3, NOW(), NOW()),
('Vegan Dessert Recipes', 'Delicious cakes and cookies that don''t require eggs or dairy.', 3, NOW(), NOW()),
('Essential Kitchen Tools', 'The only five knives and pans you actually need in your kitchen.', 3, NOW(), NOW()),
('Mastering Italian Pasta', 'How to make authentic Carbonara and Cacio e Pepe from scratch.', 3, NOW(), NOW()),

-- User 4: michael_smith (Fitness & Health)
('The Power of Weightlifting', 'Why strength training is the key to longevity and metabolic health.', 4, NOW(), NOW()),
('Marathon Training for Beginners', 'A 16-week plan to take you from the couch to your first 42k.', 4, NOW(), NOW()),
('Intermittent Fasting Myths', 'Separating scientific facts from popular marketing hype.', 4, NOW(), NOW()),
('Home Gym Setup', 'How to build an effective workout space on a limited budget.', 4, NOW(), NOW()),
('Mobility and Flexibility', 'Simple daily routines to improve your posture and prevent injuries.', 4, NOW(), NOW()),

-- User 5: emily_rose (Lifestyle & Reading)
('My Top 10 Books of 2025', 'An eclectic mix of sci-fi, history, and personal development.', 5, NOW(), NOW()),
('The Minimalism Journey', 'How decluttering my home led to a more focused and peaceful life.', 5, NOW(), NOW()),
('Building a Morning Routine', 'Small habits that changed the way I approach my workday.', 5, NOW(), NOW()),
('The Joy of Slow Living', 'Finding balance in a world that is constantly moving too fast.', 5, NOW(), NOW()),
('Creative Writing Exercises', 'Proven techniques to overcome writer''s block and find your voice.', 5, NOW(), NOW()),

-- User 6: david_miller (Finance)
('Investing for Beginners', 'How to start building wealth using low-cost index funds.', 6, NOW(), NOW()),
('The Path to Financial Freedom', 'Steps to achieve early retirement through aggressive saving.', 6, NOW(), NOW()),
('Understanding Cryptocurrencies', 'A non-technical explanation of blockchain and digital assets.', 6, NOW(), NOW()),
('Real Estate Strategies', 'Pros and cons of renting vs. buying your first investment property.', 6, NOW(), NOW()),
('Tax Planning for Freelancers', 'Smart ways to manage your income and maximize your deductions.', 6, NOW(), NOW()),

-- User 7: jessica_vance (Nature & Home)
('Urban Gardening Tips', 'How to grow organic vegetables on a small city balcony.', 7, NOW(), NOW()),
('Indoor Plant Care', 'The best low-maintenance plants for low-light apartments.', 7, NOW(), NOW()),
('Sustainable Living Hacks', 'Easy changes to reduce your plastic waste and carbon footprint.', 7, NOW(), NOW()),
('DIY Home Decor', 'Turning thrift store finds into high-end furniture pieces.', 7, NOW(), NOW()),
('Composting at Home', 'Transforming your kitchen scraps into black gold for your garden.', 7, NOW(), NOW()),

-- User 8: ryan_cooper (Cinema & Media)
('The History of Sci-Fi Film', 'From Metropolis to Dune: How the genre has evolved.', 8, NOW(), NOW()),
('The Art of Cinematography', 'Analyzing the use of light and color in modern masterpieces.', 8, NOW(), NOW()),
('Why We Love Horror', 'The psychology behind why humans enjoy being scared in theaters.', 8, NOW(), NOW()),
('Directing 101', 'Key lessons learned from the world''s most iconic filmmakers.', 8, NOW(), NOW()),
('Streaming vs. Cinema', 'Will the traditional movie theater survive the digital era?', 8, NOW(), NOW()),

-- User 9: olivia_p (Fashion)
('Building a Capsule Wardrobe', 'How to create 30 different outfits from just 10 basic pieces.', 9, NOW(), NOW()),
('The Impact of Fast Fashion', 'The environmental cost of our current clothing consumption.', 9, NOW(), NOW()),
('Vintage Shopping Secrets', 'How to find authentic designer pieces in local thrift shops.', 9, NOW(), NOW()),
('Color Theory in Style', 'Choosing the shades that best complement your skin tone.', 9, NOW(), NOW()),
('Sustainable Fabric Guide', 'What to look for: Organic cotton, linen, and recycled fibers.', 9, NOW(), NOW()),

-- User 10: kevin_dev (Gaming)
('The Rise of Indie Games', 'Why small studios are creating the most innovative experiences.', 10, NOW(), NOW()),
('PC Building Guide 2026', 'Choosing the best components for 4K gaming and streaming.', 10, NOW(), NOW()),
('The Ethics of Loot Boxes', 'Should gambling mechanics in video games be regulated?', 10, NOW(), NOW()),
('Retrogaming Emulation', 'How to play your favorite childhood classics on modern hardware.', 10, NOW(), NOW()),
('VR: The Next Frontier', 'Exploring the current state of virtual and augmented reality.', 10, NOW(), NOW()),

-- [Siguientes 50 posts para los usuarios 11-20 siguiendo el mismo formato]
('Natural Pet Training', 'Building a strong bond with your dog through positive reinforcement.', 11, NOW(), NOW()),
('Cat Behavior Explained', 'Understanding why your feline friend acts the way they do.', 11, NOW(), NOW()),
('Back End Architecture', 'Scalability patterns for high-traffic web applications.', 12, NOW(), NOW()),
('Learning React in 2026', 'Why hooks and server components are still the industry standard.', 12, NOW(), NOW()),
('Portrait Photography', 'Tips for capturing the personality of your subjects.', 13, NOW(), NOW()),
('Night Sky Landscapes', 'A beginner''s guide to long exposure astrophotography.', 13, NOW(), NOW()),
('Ancient Civilizations', 'Exploring the mysteries of the Mayan and Inca empires.', 14, NOW(), NOW()),
('The Industrial Revolution', 'How the steam engine changed the course of human history.', 14, NOW(), NOW()),
('Yoga for Stress Relief', 'A daily 15-minute sequence to calm your nervous system.', 15, NOW(), NOW()),
('Mindfulness at Work', 'Staying focused and productive in a busy office environment.', 15, NOW(), NOW()),
('Music Theory for Guitarists', 'Unlock the fretboard with scales and chord progressions.', 16, NOW(), NOW()),
('The History of Jazz', 'From the streets of New Orleans to the world stage.', 16, NOW(), NOW()),
('Watercolor Techniques', 'Mastering transparency and layering in your paintings.', 17, NOW(), NOW()),
('Modern Sculpture Trends', 'How artists are using 3D printing and new materials.', 17, NOW(), NOW()),
('Electric Vehicle Future', 'Will solid-state batteries solve the range anxiety problem?', 18, NOW(), NOW()),
('Motorcycle Maintenance', 'Basic checks you can do at home to keep your bike safe.', 18, NOW(), NOW()),
('Interior Design Basics', 'Using lighting and texture to create a cozy atmosphere.', 19, NOW(), NOW()),
('Small Space Solutions', 'Clever storage ideas for tiny apartments and studios.', 19, NOW(), NOW()),
('Particle Physics News', 'What the latest findings at CERN mean for our universe.', 20, NOW(), NOW()),
('Space Exploration 2026', 'The race to build the first permanent base on the Moon.', 20, NOW(), NOW()),

-- [Se añaden 3 posts extra por usuario para llegar a 100]
('Advanced Git Workflow', 'Using rebase and squash to keep your history clean.', 1, NOW(), NOW()),
('API Design Principles', 'Building developer-friendly RESTful services.', 1, NOW(), NOW()),
('Icelandic Road Trip', 'A 7-day itinerary through the Land of Fire and Ice.', 2, NOW(), NOW()),
('The Best Street Food', 'A culinary journey through the markets of Bangkok.', 2, NOW(), NOW()),
('Artisan Pizza at Home', 'The secret to a perfect crust in a standard oven.', 3, NOW(), NOW()),
('Global Spice Guide', 'How to use exotic spices to elevate your cooking.', 3, NOW(), NOW()),
('Strength Training Myths', 'Why you won''t get "bulky" by lifting heavy weights.', 4, NOW(), NOW()),
('The Importance of Rest', 'Why recovery is just as important as the workout.', 4, NOW(), NOW()),
('Collecting Vinyl Records', 'Why analog sound is making a huge comeback.', 5, NOW(), NOW()),
('Journaling for Mental Health', 'How writing daily can help process your emotions.', 5, NOW(), NOW()),
('Compound Interest Power', 'The mathematical reason to start saving as early as possible.', 6, NOW(), NOW()),
('Passive Income Ideas', 'Building streams of revenue that work while you sleep.', 6, NOW(), NOW()),
('Permaculture Design', 'Creating a self-sustaining ecosystem in your backyard.', 7, NOW(), NOW()),
('Eco-friendly Cleaning', 'Making your own non-toxic products with vinegar and soda.', 7, NOW(), NOW()),
('The Evolution of Animation', 'From hand-drawn cells to photorealistic CGI.', 8, NOW(), NOW()),
('Classic Noir Cinema', 'The dark aesthetics and complex heroes of the 1940s.', 8, NOW(), NOW()),
('Textile Innovation', 'How recycled plastics are becoming high-end fashion.', 9, NOW(), NOW()),
('Minimalist Footwear', 'The benefits of barefoot-style shoes for your health.', 9, NOW(), NOW()),
('The Future of eSports', 'Will competitive gaming eventually join the Olympics?', 10, NOW(), NOW()),
('Game Design Psychology', 'How developers keep players engaged through reward loops.', 10, NOW(), NOW()),
('Aquarium Aquascaping', 'Designing a beautiful underwater world for your fish.', 11, NOW(), NOW()),
('The World of Exotic Birds', 'Smartest species and how to care for them properly.', 11, NOW(), NOW()),
('Microservices vs Monolith', 'Choosing the right architecture for your team size.', 12, NOW(), NOW()),
('Typescript Best Practices', 'Writing safer and more readable frontend code.', 12, NOW(), NOW()),
('Street Photography Ethics', 'Navigating the challenges of taking photos in public.', 13, NOW(), NOW()),
('Mastering Lightroom', 'How to develop a consistent editing style for your work.', 13, NOW(), NOW()),
('The Renaissance Era', 'The explosion of art, science, and humanism in Europe.', 14, NOW(), NOW()),
('Cold War Mysteries', 'Declassified stories that changed our view of history.', 14, NOW(), NOW()),
('Breathwork Basics', 'Ancient techniques to manage stress and increase energy.', 15, NOW(), NOW()),
('The Philosophy of Stoicism', 'Applying ancient wisdom to modern digital life.', 15, NOW(), NOW()),
('Analog Synthesizers', 'Why the warm sound of the 70s is back in electronic music.', 16, NOW(), NOW()),
('Home Recording Setup', 'Producing studio-quality music in your bedroom.', 16, NOW(), NOW()),
('Ink and Charcoal Drawing', 'Expressive techniques for high-contrast illustrations.', 17, NOW(), NOW()),
('The Business of Art', 'How to sell your work and build an online brand.', 17, NOW(), NOW()),
('The History of Ferrari', 'How one man built the most iconic car brand in history.', 18, NOW(), NOW()),
('Autonomous Driving Levels', 'Understanding the path from Tesla to full automation.', 18, NOW(), NOW()),
('Feng Shui Your Bedroom', 'Optimizing your layout for better sleep and energy.', 19, NOW(), NOW()),
('Modern Industrial Style', 'Mixing raw materials like steel and brick in your home.', 19, NOW(), NOW()),
('Genetic Engineering', 'CRISPR and the future of human medicine.', 20, NOW(), NOW()),
('The Multiverse Theory', 'Is our universe just one of many in a vast bubble?', 20, NOW(), NOW());

INSERT INTO comments (text, post_id, author_id, created_at, updated_at) VALUES
-- Comments for Posts 1-10
('This guide is exactly what I needed for my final project. Thanks!', 1, 12, NOW(), NOW()),
('Great tips on security, I usually forget about the firewall rules.', 2, 5, NOW(), NOW()),
('My queries are finally running under 100ms. Amazing advice!', 3, 18, NOW(), NOW()),
('I wonder how serverless will impact the job market for DevOps.', 4, 7, NOW(), NOW()),
('Could you do a follow-up on multi-stage builds in Docker?', 5, 14, NOW(), NOW()),
('I’ve been to three of these cities and they are indeed hidden gems.', 6, 3, NOW(), NOW()),
('Traveling light changed my life, no more baggage fees!', 7, 19, NOW(), NOW()),
('The Shinjuku area is great, but Koenji is where the soul is.', 8, 11, NOW(), NOW()),
('Agreed! Street food in Hanoi is the best way to save money.', 9, 2, NOW(), NOW()),
('Insurance is the one thing you hope you never have to use.', 10, 15, NOW(), NOW()),

-- Comments for Posts 11-20
('My sourdough starter is finally bubbling. Thanks for the science!', 11, 8, NOW(), NOW()),
('The sheet-pan salmon recipe is a lifesaver on Tuesdays.', 12, 20, NOW(), NOW()),
('You won’t believe these cookies are vegan. So delicious!', 13, 6, NOW(), NOW()),
('A high-quality chef knife is worth every penny.', 14, 1, NOW(), NOW()),
('Cacio e Pepe is all about the technique, not just the ingredients.', 15, 13, NOW(), NOW()),
('Lifting heavy made me feel stronger and more energetic.', 16, 4, NOW(), NOW()),
('Following this plan! Only 10 weeks left until race day.', 17, 17, NOW(), NOW()),
('Finally someone debunking the 16:8 miracle claims.', 18, 9, NOW(), NOW()),
('An adjustable dumbbell set is a great way to save space.', 19, 10, NOW(), NOW()),
('These stretching routines really helped my lower back pain.', 20, 12, NOW(), NOW()),

-- Comments for Posts 21-30
('I just added 3 of these books to my Amazon cart.', 21, 16, NOW(), NOW()),
('Minimalism is not about having less, it’s about making room.', 22, 5, NOW(), NOW()),
('Drinking water first thing in the morning was a game changer.', 23, 14, NOW(), NOW()),
('Finding balance in the digital age is harder than it looks.', 24, 8, NOW(), NOW()),
('The "Morning Pages" exercise really helps with my block.', 25, 20, NOW(), NOW()),
('Compounding is the eighth wonder of the world indeed.', 26, 4, NOW(), NOW()),
('Financial freedom is about time, not just luxury.', 27, 11, NOW(), NOW()),
('Crypto is still too volatile for my taste, but interesting.', 28, 2, NOW(), NOW()),
('Real estate is a long game, patience is key.', 29, 19, NOW(), NOW()),
('Freelancing taxes are a nightmare without a good accountant.', 30, 7, NOW(), NOW()),

-- Comments for Posts 31-40
('I started with cherry tomatoes and now I have a whole garden.', 31, 3, NOW(), NOW()),
('My Snake Plant is the only one I haven’t killed yet.', 32, 18, NOW(), NOW()),
('Using vinegar and water is much cheaper than store cleaners.', 33, 15, NOW(), NOW()),
('That thrift store dresser turned out beautiful!', 34, 1, NOW(), NOW()),
('Composting in a small apartment is tricky but doable.', 35, 12, NOW(), NOW()),
('Metropolis is still visually stunning even today.', 36, 17, NOW(), NOW()),
('The lighting in "The Revenant" was absolutely insane.', 37, 6, NOW(), NOW()),
('I think it’s our primal instincts that make us like horror.', 38, 10, NOW(), NOW()),
('Every director should start by watching the classics.', 39, 13, NOW(), NOW()),
('Nothing beats the experience of a big screen and popcorn.', 40, 9, NOW(), NOW()),

-- Comments for Posts 41-50
('Quality over quantity is the mantra of a capsule wardrobe.', 41, 11, NOW(), NOW()),
('We need more transparency in the fashion supply chain.', 42, 2, NOW(), NOW()),
('Thrifting is like a treasure hunt, so rewarding.', 43, 15, NOW(), NOW()),
('I never realized how much blue affects my mood until now.', 44, 19, NOW(), NOW()),
('Organic linen is my favorite material for summer.', 45, 1, NOW(), NOW()),
('Hades and Hollow Knight are proof that indies are winning.', 46, 12, NOW(), NOW()),
('Wait for the new GPU series before building your PC.', 47, 14, NOW(), NOW()),
('Loot boxes should definitely be classified as gambling.', 48, 8, NOW(), NOW()),
('Emulation is vital for video game preservation.', 49, 20, NOW(), NOW()),
('AR has more potential for education than just gaming.', 50, 5, NOW(), NOW()),

-- Comments for Posts 51-100 (Continuing the pattern)
('Positive reinforcement works wonders with stubborn breeds.', 51, 16, NOW(), NOW()),
('My cat finally stopped scratching the sofa! Thank you.', 52, 4, NOW(), NOW()),
('Microservices are great but don’t start with them too early.', 53, 18, NOW(), NOW()),
('React Server Components are a bit confusing at first.', 54, 7, NOW(), NOW()),
('The 85mm lens is definitely the king of portraits.', 55, 3, NOW(), NOW()),
('Long exposure requires a really sturdy tripod.', 56, 17, NOW(), NOW()),
('The engineering behind the pyramids is still mind-blowing.', 57, 10, NOW(), NOW()),
('History repeats itself because we don’t listen to it.', 58, 13, NOW(), NOW()),
('Yoga is the best way to start a stressful Monday.', 59, 9, NOW(), NOW()),
('Focusing on one task at a time is my new rule.', 60, 6, NOW(), NOW()),
('The circle of fifths is finally making sense to me.', 61, 2, NOW(), NOW()),
('Miles Davis changed the world with "Kind of Blue".', 62, 11, NOW(), NOW()),
('Wet-on-wet technique is so hard to master but beautiful.', 63, 15, NOW(), NOW()),
('3D printing is opening so many doors for new artists.', 64, 19, NOW(), NOW()),
('Solid-state batteries will be the real turning point.', 65, 1, NOW(), NOW()),
('Check your tire pressure every month, it saves lives.', 66, 12, NOW(), NOW()),
('Adding a rug really tied my whole living room together.', 67, 14, NOW(), NOW()),
('Smart mirrors are the best storage hack for tiny bathrooms.', 68, 8, NOW(), NOW()),
('Quantum physics is basically magic that we can measure.', 69, 20, NOW(), NOW()),
('Mars is cool, but we should focus on the Moon first.', 70, 5, NOW(), NOW()),
('Interactive rebasing is a bit scary but very powerful.', 71, 16, NOW(), NOW()),
('REST is still my go-to for most small projects.', 72, 4, NOW(), NOW()),
('The Ring Road is the ultimate driving experience.', 73, 18, NOW(), NOW()),
('The Pad Thai in Chiang Mai is something else.', 74, 7, NOW(), NOW()),
('A pizza stone makes a huge difference in a home oven.', 75, 3, NOW(), NOW()),
('Smoked paprika is my secret ingredient for everything.', 76, 17, NOW(), NOW()),
('Lifting heavy won’t make women bulky, it’s a myth.', 77, 10, NOW(), NOW()),
('Rest days are when the actual muscle growth happens.', 78, 13, NOW(), NOW()),
('There is something magical about the crackle of a record.', 79, 9, NOW(), NOW()),
('Morning journaling is like clearing the cache of your brain.', 80, 6, NOW(), NOW()),
('Start as early as you can, even if it’s just $50 a month.', 81, 2, NOW(), NOW()),
('Dividends are the ultimate form of passive income.', 82, 11, NOW(), NOW()),
('Nature knows best, permaculture is the way forward.', 83, 15, NOW(), NOW()),
('Baking soda is a miracle worker for tough stains.', 84, 19, NOW(), NOW()),
('Spider-Verse really pushed the boundaries of animation.', 85, 1, NOW(), NOW()),
('Humphrey Bogart was the king of the Noir era.', 86, 12, NOW(), NOW()),
('Eco-friendly fashion is getting more affordable lately.', 87, 14, NOW(), NOW()),
('Zero-drop shoes helped my running form immensely.', 88, 8, NOW(), NOW()),
('eSports is definitely the future of entertainment.', 89, 20, NOW(), NOW()),
('The "one more turn" mechanic is dangerous for my sleep!', 90, 5, NOW(), NOW()),
('Aquascaping is like gardening but under water.', 91, 16, NOW(), NOW()),
('Parrots are incredibly smart, almost like toddlers.', 92, 4, NOW(), NOW()),
('Monoliths are easier to debug when you are a small team.', 93, 18, NOW(), NOW()),
('Zod and TypeScript together make for a great DX.', 94, 7, NOW(), NOW()),
('Always ask for permission before taking a street portrait.', 95, 3, NOW(), NOW()),
('Lightroom presets are great for starting, but learn the sliders.', 96, 17, NOW(), NOW()),
('The Medici family really knew how to fund a revolution.', 97, 10, NOW(), NOW()),
('History is written by the victors, we must read between lines.', 98, 13, NOW(), NOW()),
('Box breathing is great for anxiety during work meetings.', 99, 9, NOW(), NOW()),
('The obstacle is the way. Marcus Aurelius was a genius.', 100, 6, NOW(), NOW());

INSERT INTO comments (text, post_id, author_id, created_at, updated_at) VALUES
-- Second round of comments for Posts 1-10
('Does this security setup work with Spring Boot 3.4?', 1, 10, NOW(), NOW()),
('I tried these steps on Ubuntu 24.04 and they worked perfectly.', 2, 4, NOW(), NOW()),
('Would you recommend using B-Tree or Hash indexes for this case?', 3, 12, NOW(), NOW()),
('Cloud costs are getting out of hand, serverless is a great relief.', 4, 15, NOW(), NOW()),
('Docker Compose is still my favorite way to orchestrate locally.', 5, 2, NOW(), NOW()),
('Is it safe to visit these places during the winter season?', 6, 18, NOW(), NOW()),
('I switched to a 35L backpack and I am never going back.', 7, 9, NOW(), NOW()),
('The food at the Tsukiji outer market is still worth the hype.', 8, 14, NOW(), NOW()),
('Don’t forget to try the Khao Soi if you are in the north!', 9, 20, NOW(), NOW()),
('World Nomads has been my go-to for years now.', 10, 5, NOW(), NOW()),

-- Second round for Posts 11-20
('My bread is too dense, do you think my starter is too weak?', 11, 3, NOW(), NOW()),
('Can I substitute the salmon for tofu in this recipe?', 12, 11, NOW(), NOW()),
('The coconut milk hack for the frosting was a lifesaver.', 13, 17, NOW(), NOW()),
('How often should I professionally sharpen my Japanese knives?', 14, 8, NOW(), NOW()),
('The secret is definitely the quality of the pecorino cheese.', 15, 1, NOW(), NOW()),
('Lifting heavy cured my chronic shoulder pain. Best decision ever.', 16, 13, NOW(), NOW()),
('What is the best way to handle fueling during the long runs?', 17, 4, NOW(), NOW()),
('Fasting helped my mental clarity more than my weight loss.', 18, 16, NOW(), NOW()),
('I prefer kettlebells for a home gym, so much more versatile.', 19, 7, NOW(), NOW()),
('I finally touched my toes after three weeks of this routine!', 20, 6, NOW(), NOW()),

-- Second round for Posts 21-30
('The Martian is still the most scientifically accurate sci-fi book.', 21, 19, NOW(), NOW()),
('Decluttering your digital life is just as important as the physical.', 22, 10, NOW(), NOW()),
('I stopped checking my phone for the first hour of the day.', 23, 12, NOW(), NOW()),
('Sometimes "Slow Living" feels impossible in a corporate job.', 24, 2, NOW(), NOW()),
('Writing by hand feels so much more personal than typing.', 25, 14, NOW(), NOW()),
('Starting at 20 vs starting at 30 makes a massive difference.', 26, 15, NOW(), NOW()),
('FIRE is great, but don''t forget to enjoy the present moment.', 27, 3, NOW(), NOW()),
('The tech behind Ethereum is more interesting than the price.', 28, 18, NOW(), NOW()),
('Location, location, location. The golden rule of real estate.', 29, 9, NOW(), NOW()),
('Use an app to track every single expense, it helps a lot.', 30, 20, NOW(), NOW()),

-- Second round for Posts 31-40
('I use eggshells as fertilizer and it works like a charm.', 31, 5, NOW(), NOW()),
('Is it true that Monstera plants are toxic to cats?', 32, 11, NOW(), NOW()),
('I stopped using plastic bags entirely three years ago.', 33, 17, NOW(), NOW()),
('Where did you buy that specific shade of wood stain?', 34, 8, NOW(), NOW()),
('Bokashi bins are the best option for apartment composting.', 35, 1, NOW(), NOW()),
('Blade Runner 2049 is a modern masterpiece of the genre.', 36, 13, NOW(), NOW()),
('Roger Deakins is a god of cinematography.', 37, 4, NOW(), NOW()),
('The "jump scare" is the cheapest trick in horror movies.', 38, 16, NOW(), NOW()),
('Greta Gerwig’s direction style is so fresh and unique.', 39, 7, NOW(), NOW()),
('The sound system at IMAX theaters is worth the extra $10.', 40, 6, NOW(), NOW()),

-- Second round for Posts 41-50
('How do you deal with the "nothing to wear" feeling with fewer clothes?', 41, 19, NOW(), NOW()),
('Patagonia is one of the few brands doing it right.', 42, 10, NOW(), NOW()),
('Found a Burberry trench coat for $50 yesterday. Pure luck!', 43, 12, NOW(), NOW()),
('Yellow makes me feel energetic but I can''t wear it for long.', 44, 2, NOW(), NOW()),
('Recycled polyester still releases microplastics, unfortunately.', 45, 14, NOW(), NOW()),
('Tunic is the best indie game I played this year. Play it!', 46, 15, NOW(), NOW()),
('Don’t forget to check the clearance on your power supply.', 47, 3, NOW(), NOW()),
('Europe is doing a great job regulating these predatory mechanics.', 48, 18, NOW(), NOW()),
('The Steam Deck is the best thing to happen to emulation.', 49, 9, NOW(), NOW()),
('Using VR for history lessons would be amazing for kids.', 50, 20, NOW(), NOW()),

-- Second round for Posts 51-100
('My dog finally stopped barking at the mailman! Life saver.', 51, 5, NOW(), NOW()),
('The vertical scratching post was the solution for my cat.', 52, 11, NOW(), NOW()),
('Distributed tracing is mandatory if you go the microservices route.', 53, 17, NOW(), NOW()),
('Tailwind CSS has made my frontend workflow so much faster.', 54, 8, NOW(), NOW()),
('I prefer a 50mm for "street" portraits, feels more natural.', 55, 1, NOW(), NOW()),
('Use a remote shutter to avoid any vibration during the shot.', 56, 13, NOW(), NOW()),
('The erosion on the Sphinx suggests it might be even older.', 57, 4, NOW(), NOW()),
('Reading about the Roman Empire is my nightly ritual.', 58, 16, NOW(), NOW()),
('Child’s pose is the best way to end a long workday.', 59, 7, NOW(), NOW()),
('The "Eat the Frog" method really works for productivity.', 60, 6, NOW(), NOW()),
('Modes are still a bit confusing, but I''m getting there.', 61, 19, NOW(), NOW()),
('Nina Simone’s voice has so much raw emotion.', 62, 10, NOW(), NOW()),
('Cold-pressed paper is much better for texture.', 63, 12, NOW(), NOW()),
('NFTs might be dead, but digital art ownership is just beginning.', 64, 2, NOW(), NOW()),
('Charging infrastructure is still the biggest hurdle for EVs.', 65, 14, NOW(), NOW()),
('Change your oil every 5,000 miles, regardless of what they say.', 66, 15, NOW(), NOW()),
('Dimmable warm lights are essential for a cozy bedroom.', 67, 3, NOW(), NOW()),
('The "Marie Kondo" method for closets actually works.', 68, 18, NOW(), NOW()),
('The double-slit experiment still keeps me up at night.', 69, 9, NOW(), NOW()),
('We need to solve the radiation problem before going to Mars.', 70, 20, NOW(), NOW()),
('Squashing commits makes the PR review so much cleaner.', 71, 5, NOW(), NOW()),
('GraphQL is better for complex frontend requirements.', 72, 11, NOW(), NOW()),
('The winds in Iceland are no joke, be careful with the car doors!', 73, 17, NOW(), NOW()),
('The spicy mango salad in Bangkok is a must-try.', 74, 8, NOW(), NOW()),
('Try using a high-protein flour for a crispier pizza crust.', 75, 1, NOW(), NOW()),
('Freshly ground black pepper makes a world of difference.', 76, 13, NOW(), NOW()),
('Muscle mass is the best predictor of health in old age.', 77, 4, NOW(), NOW()),
('Active recovery like walking is better than just sitting on the couch.', 78, 16, NOW(), NOW()),
('The ritual of cleaning a record is part of the fun.', 79, 7, NOW(), NOW()),
('Journaling helps me realize my problems aren’t that big.', 80, 6, NOW(), NOW()),
('Invest in yourself first, then in the stock market.', 81, 19, NOW(), NOW()),
('REITs are a good way to get into real estate with less money.', 82, 10, NOW(), NOW()),
('Hugelkultur beds are great for retaining moisture.', 83, 12, NOW(), NOW()),
('Castile soap is another great eco-friendly alternative.', 84, 2, NOW(), NOW()),
('Studio Ghibli is the gold standard of hand-drawn animation.', 85, 14, NOW(), NOW()),
('The Big Sleep is the definitive noir film for me.', 86, 15, NOW(), NOW()),
('Piñatex (pineapple leather) is surprisingly durable.', 87, 3, NOW(), NOW()),
('Barefoot shoes took me a few months to get used to.', 88, 18, NOW(), NOW()),
('The prize pools in eSports are becoming larger than the PGA.', 89, 9, NOW(), NOW()),
('Dark Souls taught me more about persistence than school did.', 90, 20, NOW(), NOW()),
('Don’t forget the CO2 system if you want red plants.', 91, 5, NOW(), NOW()),
('African Greys have the vocabulary of a 5-year-old child.', 92, 11, NOW(), NOW()),
('Small teams should stick to a boring tech stack.', 93, 17, NOW(), NOW()),
('Interface-driven development makes testing so much easier.', 94, 8, NOW(), NOW()),
('Always carry a small printed card to explain your street photography.', 95, 1, NOW(), NOW()),
('The "H" slider in HSL is the secret to perfect skin tones.', 96, 13, NOW(), NOW()),
('The Borgias were even crazier than the Medicis.', 97, 4, NOW(), NOW()),
('History is a set of lies agreed upon. - Napoleon.', 98, 16, NOW(), NOW()),
('I do 5 minutes of box breathing before every job interview.', 99, 7, NOW(), NOW()),
('Amor Fati. Love your fate, no matter what it is.', 100, 6, NOW(), NOW());

INSERT INTO comments (text, post_id, author_id, created_at, updated_at) VALUES
-- Round 3 for Posts 1-10
('Could you share a sample configuration for Spring Security with Keycloak?', 1, 14, NOW(), NOW()),
('I struggle with the iptables rules, do you recommend UFW for beginners?', 2, 9, NOW(), NOW()),
('The explain analyze command really helped me find a sequential scan issue.', 3, 20, NOW(), NOW()),
('Is serverless actually cheaper for high-traffic consistent loads?', 4, 3, NOW(), NOW()),
('I had some issues with volume permissions on Mac, any tips?', 5, 11, NOW(), NOW()),
('I just booked a flight to one of these spots! So excited.', 6, 17, NOW(), NOW()),
('Packing cubes are the secret to fitting everything in a carry-on.', 7, 8, NOW(), NOW()),
('The subway system in Tokyo is an engineering marvel by itself.', 8, 1, NOW(), NOW()),
('I spent 2 weeks in Vietnam and the coffee was my favorite part.', 9, 13, NOW(), NOW()),
('SafetyWing has saved me a lot of money on my last trip.', 10, 4, NOW(), NOW()),

-- Round 3 for Posts 11-20
('My crust is never crunchy enough, should I use a Dutch oven?', 11, 16, NOW(), NOW()),
('Added some lemon zest to the salmon and it was a game changer.', 12, 7, NOW(), NOW()),
('Do you have a recipe for a vegan-friendly chocolate ganache?', 13, 6, NOW(), NOW()),
('A honing rod is essential to keep that edge between sharpenings.', 14, 19, NOW(), NOW()),
('Finally! A recipe that doesn’t use cream for Carbonara. Authentic!', 15, 10, NOW(), NOW()),
('I used to hate the gym, but now I can''t live without my squats.', 16, 12, NOW(), NOW()),
('The wall at mile 20 is real. Fueling is definitely the key.', 17, 2, NOW(), NOW()),
('Is it okay to drink black coffee during the fasting window?', 18, 14, NOW(), NOW()),
('Pull-up bars are the best investment for upper body strength at home.', 19, 15, NOW(), NOW()),
('My hamstrings are so tight, this routine is exactly what I needed.', 20, 3, NOW(), NOW()),

-- Round 3 for Posts 21-30
('Project Hail Mary by Andy Weir is another must-read for sci-fi fans.', 21, 18, NOW(), NOW()),
('Digital minimalism helped me reduce my screen time by 50%.', 22, 9, NOW(), NOW()),
('The "Snooze" button is the enemy of a good morning routine.', 23, 20, NOW(), NOW()),
('I find that gardening is the best way to practice slow living.', 24, 5, NOW(), NOW()),
('Does anyone have tips for starting a daily journaling habit?', 25, 1, NOW(), NOW()),
('The rule of 72 is a great way to visualize investment growth.', 26, 13, NOW(), NOW()),
('I’m aiming for Lean FIRE. Anyone else on that path?', 27, 4, NOW(), NOW()),
('Bitcoin is digital gold, but Ethereum is the digital world computer.', 28, 17, NOW(), NOW()),
('Is now a good time to buy with the current interest rates?', 29, 6, NOW(), NOW()),
('Don’t forget to set aside at least 30% for the tax man!', 30, 12, NOW(), NOW()),

-- Round 3 for Posts 31-40
('I tried growing peppers but the squirrels got to them first!', 31, 2, NOW(), NOW()),
('Pothos are practically indestructible, great for beginners.', 32, 14, NOW(), NOW()),
('Switching to a safety razor saved me so much money on blades.', 33, 15, NOW(), NOW()),
('I love the mid-century modern look you went for with that desk.', 34, 3, NOW(), NOW()),
('The liquid from the compost (compost tea) is great for plants.', 35, 18, NOW(), NOW()),
('The social commentary in "The Thing" is still so relevant.', 36, 9, NOW(), NOW()),
('The natural lighting in "The Witch" was so hauntingly beautiful.', 37, 20, NOW(), NOW()),
('Psychological horror is way scarier than gore or jump scares.', 38, 5, NOW(), NOW()),
('The screenplay is usually the most underrated part of a film.', 39, 1, NOW(), NOW()),
('I hope cinemas never go away; it''s a sacred experience.', 40, 13, NOW(), NOW()),

-- Round 3 for Posts 41-50
('I struggle with seasonal clothes in a capsule wardrobe, any advice?', 41, 4, NOW(), NOW()),
('Check out the "Good On You" app for brand ratings.', 42, 17, NOW(), NOW()),
('The quality of clothes 20 years ago was so much better than now.', 43, 6, NOW(), NOW()),
('Navy blue is my "safe" color; it goes with everything.', 44, 12, NOW(), NOW()),
('Tencel is a great sustainable alternative to traditional silk.', 45, 2, NOW(), NOW()),
('Balatro is my current indie obsession. It''s pure digital crack.', 46, 14, NOW(), NOW()),
('Cable management is the hardest part of any PC build.', 47, 15, NOW(), NOW()),
('Genshin Impact really pushed the boundaries of gacha mechanics.', 48, 3, NOW(), NOW()),
('I love playing Zelda: Ocarina of Time on my handheld.', 49, 18, NOW(), NOW()),
('Meta Quest 3 is finally making VR feel like a mainstream product.', 50, 9, NOW(), NOW()),

-- Round 3 for Posts 51-100
('Consistency is more important than the length of the training sessions.', 51, 20, NOW(), NOW()),
('The Feliway diffuser really helped my anxious cat calm down.', 52, 5, NOW(), NOW()),
('How do you handle data consistency between different microservices?', 53, 1, NOW(), NOW()),
('I finally moved from Redux to TanStack Query and I''m loving it.', 54, 13, NOW(), NOW()),
('The bokeh on that portrait lens is creamy and beautiful.', 55, 4, NOW(), NOW()),
('Astrophotography is 50% shooting and 50% post-processing.', 56, 17, NOW(), NOW()),
('The Younger Dryas impact hypothesis is a fascinating rabbit hole.', 57, 6, NOW(), NOW()),
('History is not just dates; it is the story of human nature.', 58, 12, NOW(), NOW()),
('Yoga Nidra is like a superpower for sleep deprivation.', 59, 2, NOW(), NOW()),
('The Pomodoro technique is the only way I can get through my inbox.', 60, 14, NOW(), NOW()),
('Playing the bass helped me understand rhythm so much better.', 61, 15, NOW(), NOW()),
('Thelonious Monk was a true architect of modern sound.', 62, 3, NOW(), NOW()),
('Masking fluid is a great tool for keeping those whites crisp.', 63, 18, NOW(), NOW()),
('AI-generated art is a tool, not a replacement for human soul.', 64, 9, NOW(), NOW()),
('I’m waiting for the next-gen charging speeds before I buy an EV.', 65, 20, NOW(), NOW()),
('A torque wrench is the most important tool in your garage.', 66, 5, NOW(), NOW()),
('A few well-placed mirrors can make a tiny room feel huge.', 67, 1, NOW(), NOW()),
('The "one in, one out" rule is the only way I stay organized.', 68, 13, NOW(), NOW()),
('The Big Bang theory explains the "how," but not the "why."', 69, 4, NOW(), NOW()),
('We should fix our own planet before we spend billions on Mars.', 70, 17, NOW(), NOW()),
('Force pushing is fine on your own branch, but never on main!', 71, 6, NOW(), NOW()),
('Apollo Client is a bit heavy, but it handles caching so well.', 72, 12, NOW(), NOW()),
('Don’t underestimate the gravel roads; they can be very slippery.', 73, 2, NOW(), NOW()),
('The Mango Sticky Rice is the perfect end to any Thai meal.', 74, 14, NOW(), NOW()),
('A pizza steel is actually better than a stone for heat retention.', 75, 15, NOW(), NOW()),
('Fresh basil should always be added at the very end.', 76, 3, NOW(), NOW()),
('Sarcopenia is a real threat as we age; lift those weights!', 77, 18, NOW(), NOW()),
('Sleep is the most underrated performance-enhancing drug.', 78, 9, NOW(), NOW()),
('I love the smell of old record shops. It''s nostalgic.', 79, 20, NOW(), NOW()),
('Self-reflection is the first step toward actual growth.', 80, 5, NOW(), NOW()),
('Your income is your greatest wealth-building tool.', 81, 1, NOW(), NOW()),
('Dividends are great, but total return is what matters most.', 82, 13, NOW(), NOW()),
('The ethics of food production should be a priority for everyone.', 83, 4, NOW(), NOW()),
('A mixture of baking soda and lemon works wonders on sinks.', 84, 17, NOW(), NOW()),
('Princess Mononoke is a masterpiece of environmental storytelling.', 85, 6, NOW(), NOW()),
('The cinematography in "Chinatown" is absolutely flawless.', 86, 12, NOW(), NOW()),
('Hemp is such an underrated and sustainable textile.', 87, 2, NOW(), NOW()),
('Walking uphill in barefoot shoes is a serious calf workout.', 88, 14, NOW(), NOW()),
('The production value of League of Legends tournaments is insane.', 89, 15, NOW(), NOW()),
('Elden Ring is the pinnacle of open-world game design.', 90, 3, NOW(), NOW()),
('Java moss is great for shrimp to hide and forage.', 91, 18, NOW(), NOW()),
('Owning a parrot is a 50-year commitment, not a hobby.', 92, 9, NOW(), NOW()),
('Always write code as if the person maintaining it is a psychopath.', 93, 20, NOW(), NOW()),
('Composition over inheritance is a hard lesson to learn.', 94, 5, NOW(), NOW()),
('The "decisive moment" is what every street photographer seeks.', 95, 1, NOW(), NOW()),
('I prefer Capture One for tethered shooting, but Lightroom for organizing.', 96, 13, NOW(), NOW()),
('The history of the Vatican is full of dark and twisty secrets.', 97, 4, NOW(), NOW()),
('The more you know about the past, the less you fear the future.', 98, 17, NOW(), NOW()),
('A 10-minute meditation before bed improved my sleep quality.', 99, 6, NOW(), NOW()),
('The only thing you truly control is your own reaction.', 100, 12, NOW(), NOW());

INSERT INTO comments (text, post_id, author_id, created_at, updated_at) VALUES
-- Round 4 for Posts 1-10
('Does this approach follow the latest Spring Security 6.x standards?', 1, 8, NOW(), NOW()),
('Setting up a Bastion host is also a great security layer.', 2, 16, NOW(), NOW()),
('Parallel query execution in Postgres 16 is a game changer for big data.', 3, 5, NOW(), NOW()),
('Cold starts are still a bit of a pain for Java serverless functions.', 4, 19, NOW(), NOW()),
('I prefer Podman over Docker for rootless container execution.', 5, 2, NOW(), NOW()),
('I visited Georgia recently and the mountain scenery was breathtaking.', 6, 11, NOW(), NOW()),
('Merino wool clothing is the ultimate travel hack for long trips.', 7, 14, NOW(), NOW()),
('Don’t miss the Ghibli Museum if you go to Mitaka!', 8, 20, NOW(), NOW()),
('The night markets in Taipei are even better than Bangkok in my opinion.', 9, 7, NOW(), NOW()),
('Always read the fine print on medical evacuation coverage.', 10, 15, NOW(), NOW()),

-- Round 4 for Posts 11-20
('My dough is too sticky to handle, should I reduce the hydration?', 11, 1, NOW(), NOW()),
('I swapped the butter for olive oil and the texture was still great.', 12, 18, NOW(), NOW()),
('Aquafaba is a miracle for vegan baking, have you tried it?', 13, 9, NOW(), NOW()),
('A 1000/6000 grit whetstone is all you really need for a sharp edge.', 14, 4, NOW(), NOW()),
('Guanciale is hard to find here, can I use pancetta instead?', 15, 12, NOW(), NOW()),
('Heavy compounds like deadlifts are the foundation of my routine.', 16, 17, NOW(), NOW()),
('Zone 2 training is boring but it works wonders for endurance.', 17, 6, NOW(), NOW()),
('I felt dizzy during my fast, do I need more electrolytes?', 18, 10, NOW(), NOW()),
('Resistance bands are surprisingly effective for travel workouts.', 19, 13, NOW(), NOW()),
('The Psoas stretch in this routine fixed my hip clicking.', 20, 2, NOW(), NOW()),

-- Round 4 for Posts 21-30
('Children of Time is probably the most unique sci-fi I’ve read lately.', 21, 14, NOW(), NOW()),
('The "Leave it at home" challenge for my phone was eye-opening.', 22, 5, NOW(), NOW()),
('I replaced my coffee with green tea and I feel less jittery.', 23, 11, NOW(), NOW()),
('Slow living is a mindset, not just a lifestyle choice.', 24, 1, NOW(), NOW()),
('I use the "Day One" app for digital journaling and I love it.', 25, 19, NOW(), NOW()),
('Inflation is the silent killer of savings, stay invested!', 26, 8, NOW(), NOW()),
('The 4% rule is a bit outdated with current market volatility.', 27, 20, NOW(), NOW()),
('Solana’s speed is impressive, but decentralization is the question.', 28, 4, NOW(), NOW()),
('Commercial real estate is in a weird spot right now, be careful.', 29, 15, NOW(), NOW()),
('Taxes for digital nomads are a legal gray area in many countries.', 30, 3, NOW(), NOW()),

-- Round 4 for Posts 31-40
('I started using neem oil to get rid of aphids naturally.', 31, 12, NOW(), NOW()),
('My Monstera is growing out of control, time for a moss pole!', 32, 17, NOW(), NOW()),
('Bamboo toothbrushes are a small change with a big impact.', 33, 6, NOW(), NOW()),
('That vintage lamp fits the room perfectly. Great find!', 34, 10, NOW(), NOW()),
('If your compost smells bad, you probably need more "browns."', 35, 13, NOW(), NOW()),
('The Practical Effects in "The Thing" still hold up better than CGI.', 36, 16, NOW(), NOW()),
('Wes Anderson’s symmetry is both beautiful and distracting.', 37, 7, NOW(), NOW()),
('Jump scares are okay if they are earned, not just loud noises.', 38, 18, NOW(), NOW()),
('Editing is the final rewrite of any movie.', 39, 9, NOW(), NOW()),
('I miss the days of local video rental stores sometimes.', 40, 2, NOW(), NOW()),

-- Round 4 for Posts 41-50
('Neutrals are the backbone of any good capsule wardrobe.', 41, 11, NOW(), NOW()),
('Greenwashing is everywhere, we have to stay vigilant.', 42, 14, NOW(), NOW()),
('I only buy 100% wool or cotton now, no more polyester blends.', 43, 20, NOW(), NOW()),
('Forest green is the most underrated color for winter outfits.', 44, 5, NOW(), NOW()),
('Hemp is the future of sustainable fashion, mark my words.', 45, 1, NOW(), NOW()),
('Animal Well is a masterpiece of secret-heavy game design.', 46, 19, NOW(), NOW()),
('Always install your IO shield before the motherboard!', 47, 8, NOW(), NOW()),
('The "pity" system in these games is what keeps people spending.', 48, 4, NOW(), NOW()),
('Retro achievements make replaying old games so much fun.', 49, 15, NOW(), NOW()),
('Apple Vision Pro is impressive but way too expensive for me.', 50, 3, NOW(), NOW()),

-- Round 4 for Posts 51-100
('Training a dog is 90% training the owner.', 51, 10, NOW(), NOW()),
('Puzzle feeders are great for keeping indoor cats mentally sharp.', 52, 13, NOW(), NOW()),
('The "Saga Pattern" is the best way to handle distributed transactions.', 53, 16, NOW(), NOW()),
('Zustand is so much simpler than Redux for small-to-medium apps.', 54, 7, NOW(), NOW()),
('A 35mm lens is the best for storytelling in photography.', 55, 18, NOW(), NOW()),
('Don’t forget to turn off Long Exposure Noise Reduction for stars.', 56, 9, NOW(), NOW()),
('The evidence for ancient advanced masonry is hard to ignore.', 57, 2, NOW(), NOW()),
('We can learn a lot from the fall of the Roman Republic.', 58, 12, NOW(), NOW()),
('Sun salutations are the perfect way to wake up the body.', 59, 17, NOW(), NOW()),
('I use "Forest" app to stay off my phone while working.', 60, 6, NOW(), NOW()),
('The bass is the bridge between the melody and the rhythm.', 61, 11, NOW(), NOW()),
('Herbie Hancock’s "Head Hunters" is a funk-jazz masterpiece.', 62, 14, NOW(), NOW()),
('Stretching your paper properly prevents it from buckling.', 63, 20, NOW(), NOW()),
('Artists should embrace AI as a tool, just like Photoshop back then.', 64, 5, NOW(), NOW()),
('Range anxiety is disappearing with the new 400+ mile models.', 65, 1, NOW(), NOW()),
('Always use jack stands; never trust a hydraulic jack alone.', 66, 19, NOW(), NOW()),
('Smart bulbs allowed me to set the perfect mood for reading.', 67, 8, NOW(), NOW()),
('Decluttering your digital photos is the hardest task of all.', 68, 4, NOW(), NOW()),
('The James Webb telescope is rewriting our history books.', 69, 15, NOW(), NOW()),
('Colonizing Mars is a "Plan B" we hopefully never need.', 70, 3, NOW(), NOW()),
('Conventional commits make generating changelogs so easy.', 71, 12, NOW(), NOW()),
('The React Context API is enough for most state management needs.', 72, 17, NOW(), NOW()),
('The North de-tour in Iceland is worth the extra driving hours.', 73, 6, NOW(), NOW()),
('Coconut milk in Thailand tastes nothing like the canned stuff.', 74, 10, NOW(), NOW()),
('Try cold-fermenting your dough for 72 hours for max flavor.', 75, 13, NOW(), NOW()),
('Maldon sea salt is the best finishing touch for any dish.', 76, 16, NOW(), NOW()),
('Muscle is the organ of longevity, keep training!', 77, 7, NOW(), NOW()),
('Magnesium glycinate before bed has improved my sleep deepness.', 78, 18, NOW(), NOW()),
('There is nothing like the ritual of a Saturday morning record hunt.', 79, 9, NOW(), NOW()),
('True happiness comes from internal peace, not external goals.', 80, 2, NOW(), NOW()),
('Automatic transfers to savings are the only way I actually save.', 81, 12, NOW(), NOW()),
('Growth stocks are exciting, but value stocks pay the bills.', 82, 17, NOW(), NOW()),
('Supporting local farmers is the best way to eat sustainably.', 83, 6, NOW(), NOW()),
('Vinegar and orange peels make a great-smelling cleaner.', 84, 10, NOW(), NOW()),
('Spirited Away is a beautiful allegory for growing up.', 85, 13, NOW(), NOW()),
('The "femme fatale" trope is so iconic in classic noir.', 86, 16, NOW(), NOW()),
('I love my hemp backpack, it’s practically indestructible.', 87, 7, NOW(), NOW()),
('My lower back pain disappeared after switching to minimalist shoes.', 88, 18, NOW(), NOW()),
('The prize pools in Dota 2 are absolutely mind-blowing.', 89, 9, NOW(), NOW()),
('The sense of discovery in Breath of the Wild is unmatched.', 90, 2, NOW(), NOW()),
('Duckweed is the herpes of the aquarium world, be careful!', 91, 1, NOW(), NOW()),
('Parrots need social interaction just as much as humans do.', 92, 19, NOW(), NOW()),
('Premature optimization is the root of all evil in coding.', 93, 8, NOW(), NOW()),
('The "Open-Closed Principle" is the hardest one to master.', 94, 4, NOW(), NOW()),
('Street photography is about patience and observation.', 95, 15, NOW(), NOW()),
('The grain in film photography has a soul that digital lacks.', 96, 3, NOW(), NOW()),
('The Library of Alexandria’s loss is the greatest tragedy of history.', 97, 12, NOW(), NOW()),
('We study history so we aren’t surprised by the future.', 98, 17, NOW(), NOW()),
('Consistency beats intensity every single time.', 99, 6, NOW(), NOW()),
('The quality of your life is the quality of your thoughts.', 100, 10, NOW(), NOW());

INSERT INTO comments (text, post_id, author_id, created_at, updated_at) VALUES
-- Final round for Posts 1-10
('Does this security flow handle token revocation properly?', 1, 14, NOW(), NOW()),
('I set up my first firewall thanks to this guide. Feel much safer!', 2, 6, NOW(), NOW()),
('The window functions in Postgres are so much better than doing it in JS.', 3, 19, NOW(), NOW()),
('Is there a specific framework you recommend for Go serverless?', 4, 10, NOW(), NOW()),
('Docker Init is a great new command to bootstrap projects.', 5, 2, NOW(), NOW()),
('Albania is the new hidden gem of Europe, highly recommended!', 6, 15, NOW(), NOW()),
('One bag travel is the only way to fly budget airlines stress-free.', 7, 18, NOW(), NOW()),
('The Ghibli Museum is magical, but you have to book months in advance.', 8, 4, NOW(), NOW()),
('The food scene in Seoul is mind-blowing. Don’t skip the BBQ!', 9, 11, NOW(), NOW()),
('I actually had to use my travel insurance last year, worth every cent.', 10, 13, NOW(), NOW()),

-- Final round for Posts 11-20
('My sourdough finally has those large air pockets! Success!', 11, 20, NOW(), NOW()),
('Try adding a bit of miso to the salmon glaze next time.', 12, 5, NOW(), NOW()),
('I made these for my non-vegan friends and they had no idea.', 13, 16, NOW(), NOW()),
('A ceramic honing rod is better for harder Japanese steels.', 14, 8, NOW(), NOW()),
('Pecorino Romano is the soul of this dish, don’t use Parmesan!', 15, 7, NOW(), NOW()),
('Don’t forget the mind-muscle connection, it makes a huge difference.', 16, 12, NOW(), NOW()),
('The taper week is the hardest part of marathon prep mentally.', 17, 1, NOW(), NOW()),
('Sparkling water really helps me get through the fasting window.', 18, 9, NOW(), NOW()),
('A simple pull-up bar can build a massive back if you are consistent.', 19, 3, NOW(), NOW()),
('I do this 10-minute flow every morning before my coffee.', 20, 14, NOW(), NOW()),

-- Final round for Posts 21-30
('The Three-Body Problem is a trilogy that will break your brain.', 21, 17, NOW(), NOW()),
('A "dumb phone" for the weekends is my new favorite habit.', 22, 11, NOW(), NOW()),
('Natural sunlight in the eyes within 30 mins of waking is key.', 23, 19, NOW(), NOW()),
('Slow living isn’t about doing nothing, it’s about doing things better.', 24, 2, NOW(), NOW()),
('I write three things I’m grateful for every single night.', 25, 10, NOW(), NOW()),
('The best time to invest was yesterday, the second best is today.', 26, 15, NOW(), NOW()),
('Financial independence is the ability to say "no" to things you hate.', 27, 4, NOW(), NOW()),
('L2 scaling solutions like Arbitrum are making Ethereum usable again.', 28, 6, NOW(), NOW()),
('I’m looking into house hacking as my first real estate move.', 29, 12, NOW(), NOW()),
('The "Tax Nomad" lifestyle is complicated but rewarding.', 30, 18, NOW(), NOW()),

-- Final round for Posts 31-40
('Ladybugs are great natural predators if you have a mite problem.', 31, 1, NOW(), NOW()),
('Propagation is so addictive, I have 20 baby Monsteras now!', 32, 20, NOW(), NOW()),
('Switching to bar soap instead of plastic bottles is so easy.', 33, 5, NOW(), NOW()),
('Lighting is 90% of interior design, never use the "big light"!', 34, 16, NOW(), NOW()),
('My garden is thriving thanks to the homemade compost.', 35, 7, NOW(), NOW()),
('Practical effects have a "weight" that CGI just can’t replicate.', 36, 14, NOW(), NOW()),
('The cinematography in "The Northman" was absolutely brutal.', 37, 8, NOW(), NOW()),
('Horror is the most creative genre in cinema right now.', 38, 9, NOW(), NOW()),
('A good script can save a bad director, but not the other way around.', 39, 3, NOW(), NOW()),
('The cinematic experience is about the collective energy of the crowd.', 40, 13, NOW(), NOW()),

-- Final round for Posts 41-50
('A capsule wardrobe makes getting ready in the morning so fast.', 41, 12, NOW(), NOW()),
('Buy less, but buy better. That’s the ultimate sustainable hack.', 42, 2, NOW(), NOW()),
('Linen is the only fabric I can wear during a heatwave.', 43, 17, NOW(), NOW()),
('Monochrome outfits are the easiest way to look "expensive."', 44, 11, NOW(), NOW()),
('Industrial hemp uses way less water than cotton. It’s the future.', 45, 19, NOW(), NOW()),
('The soundtrack of "Outer Wilds" is something I listen to daily.', 46, 6, NOW(), NOW()),
('If it doesn’t boot, check the RAM seating first. Always.', 47, 10, NOW(), NOW()),
('Mobile gaming is a bit of a predatory mess these days.', 48, 15, NOW(), NOW()),
('The Analogue Pocket is the ultimate way to play retro games.', 49, 4, NOW(), NOW()),
('VR fitness is actually a decent workout if you play Beat Saber.', 50, 18, NOW(), NOW()),

-- Final round for Posts 51-100
('Training your dog is the best bond-building activity.', 51, 14, NOW(), NOW()),
('Cats are solitary hunters, but they still need social play.', 52, 9, NOW(), NOW()),
('Eventual consistency is a trade-off most businesses can accept.', 53, 3, NOW(), NOW()),
('React Query handles all the "annoying" parts of data fetching.', 54, 1, NOW(), NOW()),
('I prefer the 24mm for environmental portraits. It’s more immersive.', 55, 13, NOW(), NOW()),
('The Milky Way core is only visible during certain months.', 56, 20, NOW(), NOW()),
('Ancient high technology theories are fun but need more evidence.', 57, 5, NOW(), NOW()),
('The lessons from the Stoics are still 100% applicable today.', 58, 16, NOW(), NOW()),
('Downward dog is the best stretch for a tight lower back.', 59, 7, NOW(), NOW()),
('Deep work is becoming a rare and valuable skill in our world.', 60, 12, NOW(), NOW()),
('Slapping the bass is fun, but the groove is in the ghost notes.', 61, 2, NOW(), NOW()),
('Jazz is about the notes you *don’t* play. Pure genius.', 62, 17, NOW(), NOW()),
('Always test your colors on a small scrap of paper first.', 63, 11, NOW(), NOW()),
('The artist’s eye can never be replaced by an algorithm.', 64, 19, NOW(), NOW()),
('Solid-state batteries will finally make EVs lighter and faster.', 65, 6, NOW(), NOW()),
('Keep a small fire extinguisher in your car. Better safe than sorry.', 66, 10, NOW(), NOW()),
('Smart homes should be simple; don’t over-automate the small things.', 67, 15, NOW(), NOW()),
('The feeling after a deep decluttering session is pure bliss.', 68, 4, NOW(), NOW()),
('The universe is far stranger than we can ever imagine.', 69, 18, NOW(), NOW()),
('We should probably fix the oceans before we terraform Mars.', 70, 14, NOW(), NOW()),
('A clean git history is a sign of a professional developer.', 71, 9, NOW(), NOW()),
('Signals are the new big thing in state management. Exciting!', 72, 3, NOW(), NOW()),
('The Westfjords are the most dramatic part of Iceland.', 73, 1, NOW(), NOW()),
('Eat where the locals eat, especially in Bangkok!', 74, 13, NOW(), NOW()),
('A pizza peel is essential if you don’t want to burn your hands.', 75, 20, NOW(), NOW()),
('Quality olive oil is the most important ingredient in a kitchen.', 76, 5, NOW(), NOW()),
('Strength training is the closest thing we have to an anti-aging pill.', 77, 16, NOW(), NOW()),
('Magnesium before bed is a game changer for sleep quality.', 78, 7, NOW(), NOW()),
('Buying records is an expensive but beautiful addiction.', 79, 12, NOW(), NOW()),
('You are not your thoughts; you are the observer of them.', 80, 2, NOW(), NOW()),
('The best investment you can make is in your own health.', 81, 17, NOW(), NOW()),
('Compound interest is the 8th wonder of the world.', 82, 11, NOW(), NOW()),
('Food waste is a huge problem that we can all help solve.', 83, 19, NOW(), NOW()),
('Tea tree oil is a great natural disinfectant for the bathroom.', 84, 6, NOW(), NOW()),
('Hayao Miyazaki is a master of the human spirit.', 85, 10, NOW(), NOW()),
('The atmospheric shadows in "Double Indemnity" are legendary.', 86, 15, NOW(), NOW()),
('Sustainable fashion shouldn’t be a luxury; it should be the norm.', 87, 4, NOW(), NOW()),
('Minimalist shoes helped me fix my bunions over time.', 88, 18, NOW(), NOW()),
('The atmosphere at a live eSports event is electric.', 89, 14, NOW(), NOW()),
('The "Souls" series redefined what difficulty means in games.', 90, 9, NOW(), NOW()),
('Shrimp are the best cleanup crew for any planted tank.', 91, 3, NOW(), NOW()),
('Parrots can live for 60 years, they are a lifetime commitment.', 92, 1, NOW(), NOW()),
('Write code for the next person who has to maintain it.', 93, 13, NOW(), NOW()),
('YAGNI (You Ain’t Gonna Need It) is my favorite coding principle.', 94, 20, NOW(), NOW()),
('Street photography is 10% skill and 90% persistence.', 95, 5, NOW(), NOW()),
('The dynamic range of modern digital cameras is insane.', 96, 16, NOW(), NOW()),
('The fall of Constantinople changed the world forever.', 97, 7, NOW(), NOW()),
('History is the compass that guides us through the present.', 98, 12, NOW(), NOW()),
('Consistency is the secret sauce of every successful person.', 99, 2, NOW(), NOW()),
('Your mind can be your best friend or your worst enemy. Choose wisely.', 100, 17, NOW(), NOW());